# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ea477fe4320a5eff3a29af6c029150e4fedcadbcd9038b125086803168e712d68664c831954887ac458515c75c5d24cbb7c631135165786420d38e30ab68862

test:
  secret_key_base: 094b44b9908e291be9d7621a73e5f790f627921fa1ceb1d360ac0d1e0e0399c729ce22433966c30301a02ee6dd58d2c83f9a52374b0c1577860e9621b88eb3f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
